MOCK_CREATORS = [
    {
        "account_id": "cre_001",
        "display_name": "Arjun Khanna",
        "instagram_username": "arjunlifts",
        "niche": "fitness",
        "baseline_avg_views": 25000,
        "baseline_avg_like_rate": 0.06,
        "baseline_avg_comment_rate": 0.008,
        "ig_post_count": 320,
        "ig_oldest_post_at": "2020-03-15",
        "fraud_flag_count": 0,
    },
    {
        "account_id": "cre_002",
        "display_name": "Priya Sharma",
        "instagram_username": "priyaeats",
        "niche": "food",
        "baseline_avg_views": 42000,
        "baseline_avg_like_rate": 0.08,
        "baseline_avg_comment_rate": 0.012,
        "ig_post_count": 280,
        "ig_oldest_post_at": "2021-06-22",
        "fraud_flag_count": 0,
    },
    {
        "account_id": "cre_003",
        "display_name": "Ananya Reddy",
        "instagram_username": "ananyaglow",
        "niche": "beauty",
        "baseline_avg_views": 18000,
        "baseline_avg_like_rate": 0.07,
        "baseline_avg_comment_rate": 0.010,
        "ig_post_count": 150,
        "ig_oldest_post_at": "2022-01-10",
        "fraud_flag_count": 0,
    },
    {
        "account_id": "cre_004",
        "display_name": "Rohan Mehta",
        "instagram_username": "rohanbuilds",
        "niche": "tech",
        "baseline_avg_views": 8500,
        "baseline_avg_like_rate": 0.05,
        "baseline_avg_comment_rate": 0.007,
        "ig_post_count": 95,
        "ig_oldest_post_at": "2023-04-05",
        "fraud_flag_count": 1,
    },
    {
        "account_id": "cre_005",
        "display_name": "Kavya Iyer",
        "instagram_username": "kavyadiaries",
        "niche": "lifestyle",
        "baseline_avg_views": 32000,
        "baseline_avg_like_rate": 0.09,
        "baseline_avg_comment_rate": 0.014,
        "ig_post_count": 220,
        "ig_oldest_post_at": "2021-11-18",
        "fraud_flag_count": 0,
    },
]


MOCK_BRANDS = [
    {
        "account_id": "brd_001",
        "company_name": "Oolka",
        "company_niche": "wellness beverages",
        "contact_person": "Meera Kapoor",
        "company_email": "meera@oolka.in",
    },
    {
        "account_id": "brd_002",
        "company_name": "Tatva Skincare",
        "company_niche": "ayurvedic skincare",
        "contact_person": "Vikram Joshi",
        "company_email": "vikram@tatvaskin.in",
    },
]


MOCK_CAMPAIGNS = [
    {
        "id": "camp_001",
        "company_account_id": "brd_001",
        "name": "Oolka Monsoon Hydration",
        "category": "wellness",
        "description": "Launch campaign for Oolka's new electrolyte drink range. Looking for authentic reviews from fitness and lifestyle creators showcasing the product in daily routines.",
        "Do_s": [
            "Show the product clearly in the first 3 seconds",
            "Mention the natural ingredient list",
            "Tag @oolka.in in the caption",
        ],
        "Don_ts": [
            "Do not compare directly with competitor brands by name",
            "Do not make medical or curative claims",
        ],
        "mandatory_hashtags": ["#OolkaHydrate", "#ad", "#OolkaPartner"],
        "payout_amount": 120,
        "payout_views_denominator": 1000,
        "minimum_views_required": 5000,
        "total_budget": 300000,
        "budget_consumed": 84000,
        "approval_status": "approved",
        "visible_to_users": True,
        "end_date": "2026-08-30",
    },
    {
        "id": "camp_002",
        "company_account_id": "brd_002",
        "name": "Tatva Glow Routine",
        "category": "beauty",
        "description": "Skincare routine reels featuring Tatva's new kumkumadi face serum. Targeting beauty and lifestyle creators with engaged audiences.",
        "Do_s": [
            "Show before/after lighting honestly",
            "Walk through application steps",
            "Use the exact product name 'Kumkumadi Glow Serum'",
        ],
        "Don_ts": [
            "Do not promise instant results",
        ],
        "mandatory_hashtags": ["#TatvaGlow", "#ad"],
        "payout_amount": 150,
        "payout_views_denominator": 1000,
        "minimum_views_required": 4000,
        "total_budget": 250000,
        "budget_consumed": 62000,
        "approval_status": "approved",
        "visible_to_users": True,
        "end_date": "2026-07-15",
    },
    {
        "id": "camp_003",
        "company_account_id": "brd_001",
        "name": "Oolka Pre-Workout Push",
        "category": "fitness",
        "description": "30-second reels showing Oolka pre-workout drink during gym or home workouts. Focused on tier-1 city fitness audience.",
        "Do_s": [
            "Feature the product during an actual workout",
            "Mention the caffeine and BCAA content",
        ],
        "Don_ts": [
            "Do not show product mixed with other supplement brands",
        ],
        "mandatory_hashtags": ["#OolkaPump", "#ad", "#OolkaPartner"],
        "payout_amount": 100,
        "payout_views_denominator": 1000,
        "minimum_views_required": 8000,
        "total_budget": 200000,
        "budget_consumed": 145000,
        "approval_status": "approved",
        "visible_to_users": True,
        "end_date": "2026-06-20",
    },
    {
        "id": "camp_004",
        "company_account_id": "brd_002",
        "name": "Tatva Morning Ritual",
        "category": "beauty",
        "description": "Lifestyle-led morning skincare reels featuring Tatva's full ritual range. Storytelling format preferred over plain product demos.",
        "Do_s": [
            "Show the routine in natural morning light",
            "Mention 'cold-pressed' processing",
            "Hold each product on camera for at least 2 seconds",
        ],
        "Don_ts": [
            "Do not use heavy filters that obscure the product",
            "Do not skip the disclosure hashtags",
        ],
        "mandatory_hashtags": ["#TatvaRitual", "#ad", "#TatvaPartner"],
        "payout_amount": 180,
        "payout_views_denominator": 1000,
        "minimum_views_required": 5000,
        "total_budget": 400000,
        "budget_consumed": 96000,
        "approval_status": "approved",
        "visible_to_users": True,
        "end_date": "2026-09-10",
    },
    {
        "id": "camp_005",
        "company_account_id": "brd_001",
        "name": "Oolka Office Hydration",
        "category": "wellness",
        "description": "Desk-friendly Oolka usage for working professionals. Looking for creators with audiences in IT and corporate roles.",
        "Do_s": [
            "Show the product at a real desk setup",
            "Mention sugar-free formulation",
        ],
        "Don_ts": [
            "Do not stage in obviously commercial-looking offices",
        ],
        "mandatory_hashtags": ["#OolkaAtWork", "#ad"],
        "payout_amount": 90,
        "payout_views_denominator": 1000,
        "minimum_views_required": 3000,
        "total_budget": 150000,
        "budget_consumed": 41000,
        "approval_status": "approved",
        "visible_to_users": True,
        "end_date": "2026-10-05",
    },
    {
        "id": "camp_006",
        "company_account_id": "brd_002",
        "name": "Tatva Festive Gifting",
        "category": "beauty",
        "description": "Diwali-season gifting reels featuring Tatva's premium hamper. Currently under review, not yet live to creators.",
        "Do_s": [
            "Highlight the gift packaging",
            "Mention 'limited edition festive box'",
        ],
        "Don_ts": [
            "Do not show competitor festive boxes in frame",
        ],
        "mandatory_hashtags": ["#TatvaFestive", "#ad"],
        "payout_amount": 200,
        "payout_views_denominator": 1000,
        "minimum_views_required": 10000,
        "total_budget": 500000,
        "budget_consumed": 0,
        "approval_status": "pending",
        "visible_to_users": False,
        "end_date": "2026-11-15",
    },
]


MOCK_SUBMISSIONS = [
    {
        "id": "sub_001",
        "campaign_id": "camp_001",
        "user_account_id": "cre_001",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8aQ1f2pXyZ/",
        "submission_status": "approved",
        "fraud_score": 0.08,
        "fraud_flags": [],
        "latest_snapshot": {
            "view_count": 28400,
            "like_count": 1720,
            "comment_count": 232,
        },
        "payout": {
            "approved_payout_amount": 3408,
            "payout_status": "paid",
        },
    },
    {
        "id": "sub_002",
        "campaign_id": "camp_001",
        "user_account_id": "cre_002",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8bR2g3qYzA/",
        "submission_status": "pending",
        "fraud_score": 0.11,
        "fraud_flags": [],
        "latest_snapshot": {
            "view_count": 45100,
            "like_count": 3690,
            "comment_count": 552,
        },
        "payout": None,
    },
    {
        "id": "sub_003",
        "campaign_id": "camp_002",
        "user_account_id": "cre_003",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8cS3h4rZaB/",
        "submission_status": "approved",
        "fraud_score": 0.06,
        "fraud_flags": [],
        "latest_snapshot": {
            "view_count": 19200,
            "like_count": 1380,
            "comment_count": 198,
        },
        "payout": {
            "approved_payout_amount": 2880,
            "payout_status": "paid",
        },
    },
    {
        "id": "sub_004",
        "campaign_id": "camp_002",
        "user_account_id": "cre_004",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8dT4i5sAbC/",
        "submission_status": "rejected",
        "fraud_score": 0.82,
        "fraud_flags": ["unusual_like_spike", "purchased_engagement_suspected"],
        "latest_snapshot": {
            "view_count": 9100,
            "like_count": 2840,
            "comment_count": 41,
        },
        "payout": None,
    },
    {
        "id": "sub_005",
        "campaign_id": "camp_003",
        "user_account_id": "cre_005",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8eU5j6tBcD/",
        "submission_status": "approved",
        "fraud_score": 0.04,
        "fraud_flags": [],
        "latest_snapshot": {
            "view_count": 34800,
            "like_count": 3210,
            "comment_count": 489,
        },
        "payout": {
            "approved_payout_amount": 3480,
            "payout_status": "paid",
        },
    },
    {
        "id": "sub_006",
        "campaign_id": "camp_003",
        "user_account_id": "cre_001",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8fV6k7uCdE/",
        "submission_status": "approved",
        "fraud_score": 0.09,
        "fraud_flags": [],
        "latest_snapshot": {
            "view_count": 26700,
            "like_count": 1610,
            "comment_count": 215,
        },
        "payout": {
            "approved_payout_amount": 2670,
            "payout_status": "processing",
        },
    },
    {
        "id": "sub_007",
        "campaign_id": "camp_004",
        "user_account_id": "cre_002",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8gW7l8vDeF/",
        "submission_status": "pending",
        "fraud_score": 0.07,
        "fraud_flags": [],
        "latest_snapshot": {
            "view_count": 41200,
            "like_count": 3380,
            "comment_count": 502,
        },
        "payout": None,
    },
    {
        "id": "sub_008",
        "campaign_id": "camp_004",
        "user_account_id": "cre_003",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8hX8m9wEfG/",
        "submission_status": "approved",
        "fraud_score": 0.05,
        "fraud_flags": [],
        "latest_snapshot": {
            "view_count": 17600,
            "like_count": 1260,
            "comment_count": 181,
        },
        "payout": {
            "approved_payout_amount": 3168,
            "payout_status": "paid",
        },
    },
    {
        "id": "sub_009",
        "campaign_id": "camp_005",
        "user_account_id": "cre_004",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8iY9n0xFgH/",
        "submission_status": "rejected",
        "fraud_score": 0.71,
        "fraud_flags": ["unusual_like_spike"],
        "latest_snapshot": {
            "view_count": 7400,
            "like_count": 1980,
            "comment_count": 28,
        },
        "payout": None,
    },
    {
        "id": "sub_010",
        "campaign_id": "camp_005",
        "user_account_id": "cre_005",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8jZ0o1yGhI/",
        "submission_status": "approved",
        "fraud_score": 0.06,
        "fraud_flags": [],
        "latest_snapshot": {
            "view_count": 31500,
            "like_count": 2920,
            "comment_count": 442,
        },
        "payout": {
            "approved_payout_amount": 2835,
            "payout_status": "paid",
        },
    },
    {
        "id": "sub_011",
        "campaign_id": "camp_002",
        "user_account_id": "cre_001",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8kA1p2zHiJ/",
        "submission_status": "approved",
        "fraud_score": 0.10,
        "fraud_flags": [],
        "latest_snapshot": {
            "view_count": 24300,
            "like_count": 1480,
            "comment_count": 196,
        },
        "payout": {
            "approved_payout_amount": 3645,
            "payout_status": "processing",
        },
    },
    {
        "id": "sub_012",
        "campaign_id": "camp_005",
        "user_account_id": "cre_002",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8lB2q3aIjK/",
        "submission_status": "approved",
        "fraud_score": 0.07,
        "fraud_flags": [],
        "latest_snapshot": {
            "view_count": 43800,
            "like_count": 3570,
            "comment_count": 528,
        },
        "payout": {
            "approved_payout_amount": 3942,
            "payout_status": "paid",
        },
    },
    {
        "id": "sub_013",
        "campaign_id": "camp_001",
        "user_account_id": "cre_003",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8mC3r4bJkL/",
        "submission_status": "pending",
        "fraud_score": 0.12,
        "fraud_flags": [],
        "latest_snapshot": {
            "view_count": 18900,
            "like_count": 1340,
            "comment_count": 187,
        },
        "payout": None,
    },
    {
        "id": "sub_014",
        "campaign_id": "camp_003",
        "user_account_id": "cre_004",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8nD4s5cKlM/",
        "submission_status": "approved",
        "fraud_score": 0.38,
        "fraud_flags": ["unusual_like_spike"],
        "latest_snapshot": {
            "view_count": 8900,
            "like_count": 510,
            "comment_count": 63,
        },
        "payout": {
            "approved_payout_amount": 890,
            "payout_status": "processing",
        },
    },
    {
        "id": "sub_015",
        "campaign_id": "camp_001",
        "user_account_id": "cre_005",
        "platform": "instagram",
        "content_link": "https://instagram.com/p/C8oE5t6dLmN/",
        "submission_status": "approved",
        "fraud_score": 0.05,
        "fraud_flags": [],
        "latest_snapshot": {
            "view_count": 33200,
            "like_count": 3070,
            "comment_count": 458,
        },
        "payout": {
            "approved_payout_amount": 3984,
            "payout_status": "paid",
        },
    },
]
